// src/utils/videoData.js
// Example static video data for your YouTube clone

export const videoData = [
  {
    id: '1',
    title: 'React Tutorial for Beginners',
    channel: 'Code Academy',
    views: '1.2M',
    date: '1 week ago',
    thumbnail: 'https://i.ytimg.com/vi/dGcsHMXbSOA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA',
    category: 'ReactJS',
    likes: 0,
  },
  {
    id: '2',
    title: 'Learn JavaScript in 1 Hour',
    channel: 'JS Mastery',
    views: '900K',
    date: '2 days ago',
    thumbnail: 'https://i.ytimg.com/vi/W6NZfCO5SIk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/W6NZfCO5SIk',
    category: 'JavaScript',
    likes: 0,
  },
  {
    id: '3',
    title: 'CSS Flexbox Crash Course',
    channel: 'DesignCourse',
    views: '500K',
    date: '3 days ago',
    thumbnail: 'https://i.ytimg.com/vi/JJSoEo8JSnc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/JJSoEo8JSnc',
    category: 'CSS',
    likes: 0,
  },
  {
    id: '4',
    title: 'Node.js Crash Course',
    channel: 'Traversy Media',
    views: '800K',
    date: '5 days ago',
    thumbnail: 'https://i.ytimg.com/vi/fBNz5xF-Kx4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4',
    category: 'NodeJS',
    likes: 0,
  },
  {
    id: '5',
    title: 'Python for Beginners',
    channel: 'Programming with Mosh',
    views: '1.5M',
    date: '1 month ago',
    thumbnail: 'https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/_uQrJ0TkZlc',
    category: 'Python',
    likes: 0,
  },
  {
    id: '6',
    title: 'HTML Full Course - Build a Website Tutorial',
    channel: 'freeCodeCamp.org',
    views: '2M',
    date: '2 months ago',
    thumbnail: 'https://i.ytimg.com/vi/pQN-pnXPaVg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/pQN-pnXPaVg',
    category: 'HTML',
    likes: 0,
  },
  {
    id: '7',
    title: 'Vue JS Crash Course',
    channel: 'Net Ninja',
    views: '600K',
    date: '3 weeks ago',
    thumbnail: 'https://i.ytimg.com/vi/FXpIoQ_rT_c/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/FXpIoQ_rT_c',
    category: 'VueJS',
    likes: 0,
  },
  {
    id: '8',
    title: 'Angular Tutorial for Beginners',
    channel: 'Programming with Mosh',
    views: '700K',
    date: '2 weeks ago',
    thumbnail: 'https://i.ytimg.com/vi/k5E2AVpwsko/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/k5E2AVpwsko',
    category: 'Angular',
    likes: 0,
  },
  {
    id: '9',
    title: 'TypeScript Tutorial for Beginners',
    channel: 'Academind',
    views: '400K',
    date: '4 days ago',
    thumbnail: 'https://i.ytimg.com/vi/BwuLxPH8IDs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs',
    category: 'TypeScript',
    likes: 0,
  },
  {
    id: '10',
    title: 'SASS Tutorial for Beginners',
    channel: 'The Net Ninja',
    views: '350K',
    date: '1 week ago',
    thumbnail: 'https://i.ytimg.com/vi/_a5j7KoflTs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/_a5j7KoflTs',
    category: 'SASS',
    likes: 0,
  },
  {
    id: '11',
    title: 'Bootstrap 5 Crash Course',
    channel: 'Traversy Media',
    views: '300K',
    date: '6 days ago',
    thumbnail: 'https://i.ytimg.com/vi/4sosXZsdy-s/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/4sosXZsdy-s',
    category: 'Bootstrap',
    likes: 0,
  },
  // Music Section
  {
    id: '12',
    title: 'Ed Sheeran - Shape of You [Official Video]',
    channel: 'Ed Sheeran',
    views: '6B',
    date: '5 years ago',
    thumbnail: 'https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/JGwWNGJdvx8',
    category: 'Music',
    likes: 0,
  },
  {
    id: '13',
    title: 'The Weeknd - Blinding Lights (Official Video)',
    channel: 'The Weeknd',
    views: '800M',
    date: '3 years ago',
    thumbnail: 'https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/4NRXx6U8ABQ',
    category: 'Music',
    likes: 0,
  },
  {
    id: '14',
    title: 'Imagine Dragons - Believer',
    channel: 'ImagineDragonsVEVO',
    views: '2.5B',
    date: '6 years ago',
    thumbnail: 'https://i.ytimg.com/vi/7wtfhZwyrcc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/7wtfhZwyrcc',
    category: 'Music',
    likes: 0,
  },
  // Movie Section
  {
    id: '15',
    title: 'Avengers: Endgame | Final Trailer',
    channel: 'Marvel Entertainment',
    views: '150M',
    date: '5 years ago',
    thumbnail: 'https://i.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/TcMBFSGVi1c',
    category: 'Movie',
    likes: 0,
  },
  {
    id: '16',
    title: 'Inception (2010) Official Trailer #1',
    channel: 'Movieclips Classic Trailers',
    views: '100M',
    date: '13 years ago',
    thumbnail: 'https://i.ytimg.com/vi/YoHD9XEInc0/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/YoHD9XEInc0',
    category: 'Movie',
    likes: 0,
  },
  {
    id: '17',
    title: 'JOKER - Final Trailer',
    channel: 'Warner Bros. Pictures',
    views: '80M',
    date: '5 years ago',
    thumbnail: 'https://i.ytimg.com/vi/zAGVQLHvwOY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/zAGVQLHvwOY',
    category: 'Movie',
    likes: 0,
  },
];
